name: Sphinx

on: 
  push:

jobs:
  Sphinx-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install sphinx
    - name: Build-html
      run: |
        sphinx-build -b html docs docs/html
    - name: push-html
      run: |
        git config --global user.email "13309694136@163.com"
        git config --global user.name "acse-0541de58"
        git pull
        git add docs/html/
        git commit -a -m "New html"
        git push
