name: PEP8
on:
  push:


jobs:
  flask8:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      # Runs a set of commands using the runners shell
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install flake8
      
      - name: Lint with flake8
        run: |
          pycodestyle .
